version: "3"

services:


  wordpress:
    image: wordpress:6.4.2
    container_name: wordpress
    expose:
      - "80"    
    restart: unless-stopped
    depends_on:
      - mysql 
    volumes:
      - ./wordpress:/var/www/html
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}  
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
#      VIRTUAL_HOST: tudominio.com        #debe ser un dominio válido y DNS apuntando a este servidor
#      LETSENCRYPT_HOST: tudominio.com    #debe ser un dominio válido y DNS apuntando a este servidor   

  mysql:
    image: mariadb
    container_name: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
    env_file: .env 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}    

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: wppma 
    restart: unless-stopped   
    depends_on:      
      - mysql
    ports:      
      - "8080:80"        
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD} 

  nginx-proxy:
    image: nginx:1.15.12-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d      
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - wordpress
    restart: unless-stopped    
  
      



      

 
